# this job is for temporary testing and making sure latents.csv was written correctly. The combination of cell_id and timestep should uniquely determine an image in the dataset, thus also a latent vector (latent vecs can be the same in practice but two entries with the same keys should map to the same latent)
# test_latent_keys.sub
   
docker_image = jenslundsgaard/tphate:latest
universe = docker

executable = /bin/bash
arguments = ./test_latent_keys.sh 
	
log = test_latent_keys_$(Cluster)_$(Process).log
error =  test_latent_keys_$(Cluster)_$(Process).err
output =  test_latent_keys_$(Cluster)_$(Process).out
# Transfer our executable script
transfer_input_files = test_latent_keys.sh, test_latent_keys.py, file:///staging/groups/bhaskar_group/ivf/latents.csv
 
request_cpus = 1
request_memory = 80GB
request_disk = 32GB

queue 1
