
# tphate_test.sub
   
docker_image = jenslundsgaard/tphate:latest
#docker_image = pytorch/pytorch:2.9.0-cuda12.8-cudnn9-runtime
universe = docker
# Specify your executable (single binary or a script that runs several
#  commands) and arguments to be passed to jobs. 
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
shell = ./tphate_test.sh
	
# Specify the name of the log, standard error, and standard output (or
# "screen output") files. Wherever you see $(Cluster), HTCondor will insert the 
#  queue number assigned to this set of jobs at the time of submission.
log = tphate_test_$(Cluster)_$(Process).log
error =  tphate_test_$(Cluster)_$(Process).err
output = tphate_test_$(Cluster)_$(Process).out
# Transfer our executable script
transfer_input_files = tphate_test.sh, tphate_test.py
#train_requirements.txt
#Requirements = (Machine == "bhaskargpu4000.chtc.wisc.edu") && (DriverVersion == "12.8") && (DeviceName == "NVIDIA H200")
 
#+GPUModel = "NVIDIA H200"
# Requirements (e.g., operating system) your job needs, what amount of
# compute resources each job will need on the computer where it runs.
request_cpus = 1
request_memory = 8GB
request_disk = 16GB


queue 1
