#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo "
echo ""
echo "   grep -E '(Processing|Saved|Completed|embryo|✓)' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "
echo ""
echo ""
echo "   find /staging/groups/bhaskar_group/rho9/ -name '*.npy' -path '*latent*' 2>/dev/null"
echo "   find /staging/groups/bhaskar_group/rho9/ -name 'embryo_*.npy' 2>/dev/null"
echo ""
echo "   find /staging/groups/bhaskar_group/rho9/ -name 'extraction_progress.log' 2>/dev/null"
echo ""
echo "============================================================"
echo ""
echo "
echo "   grep -c 'Processing embryo' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "
echo "   grep -c 'Saved:' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "
echo "   grep -i 'error\|failed\|exception' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null | tail -20"
echo ""
echo "============================================================"

