#!/bin/bash
# 檢查 CHTC 上的 latent extraction 任務狀態

echo "============================================================"
echo "CHTC Latent Extraction 任務狀態檢查"
echo "============================================================"
echo ""
echo "請在 CHTC 上依序執行以下命令："
echo ""
echo "1. 檢查當前運行的任務："
echo "   condor_q -submitter rho9 | grep -E '(ID|extract)'"
echo ""
echo "2. 檢查最近完成的任務："
echo "   condor_history -limit 10 -submitter rho9 | grep extract"
echo ""
echo "3. 檢查任務日誌是否存在："
echo "   ls -lh ~/logs/extract_latents_v1_baseline.* 2>/dev/null || echo '日誌不存在'"
echo ""
echo "4. 查看輸出日誌（如果存在）："
echo "   tail -100 ~/logs/extract_latents_v1_baseline.out 2>/dev/null || echo '輸出日誌不存在'"
echo ""
echo "5. 查看錯誤日誌（如果存在）："
echo "   tail -100 ~/logs/extract_latents_v1_baseline.err 2>/dev/null || echo '錯誤日誌不存在'"
echo ""
echo "6. 檢查 staging 目錄結構："
echo "   ls -lh /staging/groups/bhaskar_group/rho9/ 2>/dev/null | head -20"
echo ""
echo "7. 搜索所有可能的結果位置："
echo "   find /staging/groups/bhaskar_group/rho9/ -name '*latent*' -o -name '*v1_baseline*' 2>/dev/null | head -20"
echo ""
echo "8. 檢查 submit 文件是否存在："
echo "   ls -lh ~/extract_latents*.sub 2>/dev/null || echo 'submit 文件不存在'"
echo ""
echo "============================================================"

