#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep -c 'Processing embryo' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null || echo '0'"
echo ""
echo "   grep -c 'Saved:' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null || echo '0'"
echo ""
echo "   grep 'Processing embryo' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null | head -20"
echo ""
echo "   grep 'Saved:' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null | head -20"
echo ""
echo "   grep -E 'Output directory|Created directory|mkdir' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "   tail -50 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   python3 analyze_extraction_log.py /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"
echo "============================================================"

