#!/bin/bash

echo "=========================================="
echo "=========================================="
echo ""
echo ""
echo "  ssh rho9@ap2001.chtc.wisc.edu"
echo ""
echo ""
echo "
echo "  ls -lh /staging/groups/bhaskar_group/"
echo ""
echo "
echo "  ls -ld /staging/groups/bhaskar_group/*/"
echo ""
echo "
echo "  du -sh /staging/groups/bhaskar_group/*/"
echo ""
echo "
echo "  tree -L 2 -h /staging/groups/bhaskar_group/ 2>/dev/null || find /staging/groups/bhaskar_group/ -maxdepth 2 -type d | head -50"
echo ""
echo "
echo "  ls -lh /staging/groups/bhaskar_group/rho9/"
echo ""
echo "=========================================="
echo "=========================================="
echo ""
echo "
echo "ssh rho9@ap2001.chtc.wisc.edu 'ls -lh /staging/groups/bhaskar_group/'"
echo ""
echo "
echo "ssh rho9@ap2001.chtc.wisc.edu 'ls -ld /staging/groups/bhaskar_group/*/'"
echo ""
echo "
echo "ssh rho9@ap2001.chtc.wisc.edu 'du -sh /staging/groups/bhaskar_group/*/'"
echo ""

