#!/bin/bash
# 檢查任務實際狀態

echo "============================================================"
echo "檢查任務實際狀態"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  查看任務運行時間和狀態："
echo "   condor_q -long 2852953.0 | grep -E 'JobStatus|RemoteHost|RemoteStartTime|JobCurrentStartDate'"
echo ""
echo "2️⃣  使用 condor_tail 查看最新的輸出（最準確）："
echo "   condor_tail 2852953.0 | tail -30"
echo ""
echo "3️⃣  檢查任務是否重啟過（查看 condor 日誌）："
echo "   grep -E 'Job executing|Job terminated|Job was evicted|Job was held' ~/logs/extract_latents_v1_baseline.log | tail -10"
echo ""
echo "4️⃣  查看最新的實時輸出："
echo "   condor_tail -f 2852953.0"
echo ""
echo "============================================================"
echo "關於日誌重複的可能原因："
echo "  1. 任務重啟了（被 evicted 然後重新開始）"
echo "  2. 日誌輸出緩衝問題（輸出被重複打印）"
echo "  3. 任務實際上已經完成了 sequence 2，只是輸出顯示有延遲"
echo ""
echo "使用 condor_tail 可以獲取最新的實際狀態"
echo "============================================================"

