#!/bin/bash
# 檢查並重啟任務

echo "============================================================"
echo "檢查當前狀況並重啟任務"
echo "============================================================"
echo ""
echo "問題分析："
echo "  - staging 上的腳本是正確的"
echo "  - 但任務執行時使用的是舊的副本"
echo "  - 任務仍在運行但可能已經失敗"
echo ""
echo "請在 CHTC 上執行："
echo ""
echo "1. 確認 staging 上的腳本正確："
echo "   head -5 /staging/groups/bhaskar_group/rho9/extract_latents.sh"
echo ""
echo "2. 檢查當前任務狀態："
echo "   condor_q 2852953.0"
echo ""
echo "3. 查看實時日誌（看任務現在在做什麼）："
echo "   condor_tail -f 2852953.0"
echo ""
echo "4. 如果任務已經失敗或卡住，移除並重新提交："
echo "   condor_rm 2852953.0"
echo "   condor_submit ~/extract_latents_from_home.sub"
echo ""
echo "5. 新任務會使用更新後的腳本（因為從 staging 複製）"
echo ""
echo "============================================================"
echo ""
echo "注意：新任務會從 staging 複製最新的腳本，所以應該沒問題。"
echo "============================================================"

