#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo ""
echo "   condor_q -better-analyze 2851275.0"
echo ""
echo "   tail -50 ~/logs/extract_latents_v1_baseline.log"
echo ""
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.err"
echo ""
echo "   condor_q -better-analyze 2851275.0 | grep -A 10 'Requirements'"
echo ""
echo "============================================================"
echo ""
echo ""
echo "  /staging/groups/bhaskar_group/rho9/model_latents/v1_baseline/"
echo "============================================================"

