#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   condor_q -submitter rho9 | grep -E '(ID|extract)'"
echo ""
echo "   condor_history -limit 10 -submitter rho9 | grep extract"
echo ""
echo ""
echo ""
echo ""
echo "   ls -lh /staging/groups/bhaskar_group/rho9/ 2>/dev/null | head -20"
echo ""
echo "   find /staging/groups/bhaskar_group/rho9/ -name '*latent*' -o -name '*v1_baseline*' 2>/dev/null | head -20"
echo ""
echo ""
echo "============================================================"

