#!/bin/bash
# 檢查 pandas 問題和任務狀態

echo "============================================================"
echo "檢查任務狀態和 pandas 問題"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  檢查任務是否還在運行："
echo "   condor_q -submitter rho9"
echo ""
echo "2️⃣  查看完整的輸出日誌（看是否真的失敗）："
echo "   tail -100 ~/logs/extract_latents_v1_baseline.out"
echo "   # 或"
echo "   tail -100 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "3️⃣  查看錯誤日誌："
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo "   # 或"
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.err"
echo ""
echo "4️⃣  搜索 pandas 相關的錯誤："
echo "   grep -i 'pandas\|import.*pandas' ~/logs/extract_latents_v1_baseline.out | tail -20"
echo ""
echo "5️⃣  檢查是否有成功處理的記錄："
echo "   grep -c 'Processing embryo' ~/logs/extract_latents_v1_baseline.out"
echo "   grep -c 'Saved:' ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"
echo "關於 pandas 的問題："
echo "  - 如果 Python 腳本中已經有 pandas，可能不會完全失敗"
echo "  - 需要查看完整日誌來確認是否真的失敗"
echo "  - 如果失敗，可能需要修復 pandas 安裝問題"
echo "============================================================"

