#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   condor_q -better-analyze 2852953.0 | grep -A 10 'HoldReason'"
echo ""
echo "   condor_q -long 2852953.0 | grep -E 'HoldReason|HoldCode|LastHoldReason'"
echo ""
echo "   grep '2852953' ~/logs/extract_latents_v1_baseline.log | grep -i 'hold\|evicted\|terminated' | tail -10"
echo ""
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "============================================================"
    echo ""
echo "============================================================"
