#!/bin/bash
# 檢查是否有成功提取的記錄

echo "============================================================"
echo "檢查是否有成功提取胚胎的記錄"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  查看完整輸出日誌（檢查是否有成功提取）："
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "2️⃣  快速檢查（統計處理和保存的數量）："
echo "   echo '處理的胚胎數：'"
echo "   grep -c 'Processing embryo' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null || echo '0'"
echo ""
echo "   echo '保存的文件數：'"
echo "   grep -c 'Saved:' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null || echo '0'"
echo ""
echo "3️⃣  查看所有成功處理的胚胎ID："
echo "   grep 'Processing embryo' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null | head -20"
echo ""
echo "4️⃣  查看保存記錄："
echo "   grep 'Saved:' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null | head -20"
echo ""
echo "5️⃣  檢查目錄創建記錄："
echo "   grep -E 'Output directory|Created directory|mkdir' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "6️⃣  查看日誌最後50行（看任務結束時的狀態）："
echo "   tail -50 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "7️⃣  使用 Python 腳本詳細分析（如果已上傳）："
echo "   python3 analyze_extraction_log.py /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"
echo "如果發現有成功提取的記錄，但結果目錄不存在，可能的原因："
echo "  - 結果保存在任務工作目錄，但任務被終止後被清理了"
echo "  - transfer_output_remaps 沒有正常工作"
echo "  - 目錄創建在工作目錄而不是 staging"
echo "============================================================"

