#!/bin/bash
# 檢查實際進度

echo "============================================================"
echo "檢查任務實際進度"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  查看日誌實際內容（最後50行）："
echo "   tail -50 ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "2️⃣  搜索不同的匹配模式："
echo "   grep 'Processing' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo "   grep 'Saved' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo "   grep 'embryo' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo ""
echo "3️⃣  檢查日誌文件大小（看是否在增長）："
echo "   ls -lh ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "4️⃣  查看完整的日誌內容（如果不太長）："
echo "   wc -l ~/logs/extract_latents_v1_baseline.out"
echo "   # 如果行數不多，可以查看全部："
echo "   cat ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "5️⃣  檢查是否有結果目錄（即使部分完成）："
echo "   ls -lh /staging/groups/bhaskar_group/rho9/model_latents/v1_baseline/ 2>/dev/null || echo '目錄不存在'"
echo ""
echo "============================================================"

