#!/bin/bash
# 檢查任務詳細狀態和日誌

echo "============================================================"
echo "任務狀態分析"
echo "============================================================"
echo ""
echo "任務 ID: 2851275.0 目前處於 IDLE 狀態（等待資源）"
echo ""
echo "請在 CHTC 上執行以下命令查看詳細信息："
echo ""
echo "1️⃣  查看任務詳細狀態："
echo "   condor_q -better-analyze 2851275.0"
echo ""
echo "2️⃣  查看最新的日誌內容（home 目錄）："
echo "   tail -50 ~/logs/extract_latents_v1_baseline.log"
echo ""
echo "3️⃣  查看 staging 目錄的日誌內容："
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.err"
echo ""
echo "4️⃣  查看任務為什麼在等待（可能需要 GPU）："
echo "   condor_q -better-analyze 2851275.0 | grep -A 10 'Requirements'"
echo ""
echo "============================================================"
echo ""
echo "任務在 IDLE 狀態的可能原因："
echo "  - 等待 GPU 資源（GPU 可能正在被其他任務使用）"
echo "  - 等待滿足機器要求（bhaskargpu4000.chtc.wisc.edu）"
echo "  - 系統資源暫時不足"
echo ""
echo "當任務開始運行時，結果會保存在："
echo "  /staging/groups/bhaskar_group/rho9/model_latents/v1_baseline/"
echo "============================================================"

