#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   condor_q -submitter rho9"
echo ""
echo "   tail -100 ~/logs/extract_latents_v1_baseline.out"
echo "
echo "   tail -100 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo "
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.err"
echo ""
echo "   grep -i 'pandas\|import.*pandas' ~/logs/extract_latents_v1_baseline.out | tail -20"
echo ""
echo "   grep -c 'Processing embryo' ~/logs/extract_latents_v1_baseline.out"
echo "   grep -c 'Saved:' ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"
echo "============================================================"

