#!/bin/bash
# 檢查錯誤日誌

echo "============================================================"
echo "檢查錯誤日誌"
echo "============================================================"
echo ""
echo "請執行："
echo ""
echo "1. 查看錯誤日誌："
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "2. 如果錯誤日誌是空的，查看 condor 日誌中的錯誤："
echo "   grep -iE 'error|failed|exception|traceback' ~/logs/extract_latents_v1_baseline.log | tail -20"
echo ""
echo "3. 檢查是否有任何警告："
echo "   grep -i 'warning\|timeout\|slow' ~/logs/extract_latents_v1_baseline.log | tail -10"
echo ""
echo "============================================================"
echo "根據資源使用情況："
echo "  - GPU 記憶體使用正常（908MB）"
echo "  - 系統記憶體使用正常（908MB）"
echo "  - 沒有資源不足的問題"
echo ""
echo "可能的原因："
echo "  1. 數據載入非常慢（從 staging 讀取圖像）"
echo "  2. 第一個 sequence 2 特別慢（初始化開銷）"
echo "  3. 輸出緩衝（實際已經完成但沒有輸出）"
echo ""
echo "建議："
echo "  - 如果沒有錯誤，可以再等10-15分鐘"
echo "  - 或者查看錯誤日誌確認是否有問題"
echo "============================================================"

