#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo ""
echo "   head -5 /staging/groups/bhaskar_group/rho9/extract_latents.sh"
echo ""
echo "   condor_q 2852953.0"
echo ""
echo "   condor_tail -f 2852953.0"
echo ""
echo "   condor_rm 2852953.0"
echo "   condor_submit ~/extract_latents_from_home.sub"
echo ""
echo ""
echo "============================================================"
echo ""
echo "============================================================"

