#!/bin/bash
# 檢查是否有成功提取的記錄和部分結果

echo "============================================================"
echo "檢查 Latent Extraction 進度和結果"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令檢查："
echo ""
echo "1️⃣  查看完整的輸出日誌（查找成功提取的記錄）："
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo "   # 或"
echo "   tail -200 ~/logs/extract_latents_v1_baseline.out 2>/dev/null || echo '日誌不存在'"
echo ""
echo "2️⃣  搜索是否有成功提取的記錄："
echo "   grep -E '(Processing|Saved|Completed|embryo|✓)' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "3️⃣  檢查任務工作目錄中是否有臨時結果（如果任務還在運行）："
echo "   # 這個需要在任務執行機器上查看，通常已經被清理了"
echo ""
echo "4️⃣  檢查 staging 目錄結構（看看是否有部分創建的目錄）："
echo "   ls -laR /staging/groups/bhaskar_group/rho9/model_latents/ 2>/dev/null || echo '目錄不存在'"
echo ""
echo "5️⃣  搜索所有可能的結果文件："
echo "   find /staging/groups/bhaskar_group/rho9/ -name '*.npy' -path '*latent*' 2>/dev/null"
echo "   find /staging/groups/bhaskar_group/rho9/ -name 'embryo_*.npy' 2>/dev/null"
echo ""
echo "6️⃣  檢查腳本中是否有 progress log："
echo "   find /staging/groups/bhaskar_group/rho9/ -name 'extraction_progress.log' 2>/dev/null"
echo ""
echo "============================================================"
echo "從日誌中提取關鍵信息："
echo ""
echo "   # 查看處理了多少個胚胎"
echo "   grep -c 'Processing embryo' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "   # 查看保存了多少個文件"
echo "   grep -c 'Saved:' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "   # 查看是否有錯誤"
echo "   grep -i 'error\|failed\|exception' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null | tail -20"
echo ""
echo "============================================================"

