#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   tail -50 ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep 'Processing' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo "   grep 'Saved' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo "   grep 'embryo' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo ""
echo "   ls -lh ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "   wc -l ~/logs/extract_latents_v1_baseline.out"
echo "
echo "   cat ~/logs/extract_latents_v1_baseline.out"
echo ""
echo ""
echo "============================================================"

