#!/bin/bash
# 查看整个 bhaskar_group 的 staging 目录

echo "=========================================="
echo "📁 查看整个 Bhaskar Group 的 Staging 目录"
echo "=========================================="
echo ""
echo "请先 SSH 连接到 CHTC 服务器："
echo ""
echo "  ssh rho9@ap2001.chtc.wisc.edu"
echo ""
echo "连接后，运行以下命令查看整个小组的目录："
echo ""
echo "  # 查看整个 bhaskar_group 目录结构"
echo "  ls -lh /staging/groups/bhaskar_group/"
echo ""
echo "  # 查看所有成员的目录"
echo "  ls -ld /staging/groups/bhaskar_group/*/"
echo ""
echo "  # 查看每个成员的目录大小"
echo "  du -sh /staging/groups/bhaskar_group/*/"
echo ""
echo "  # 查看详细的目录树（前50行）"
echo "  tree -L 2 -h /staging/groups/bhaskar_group/ 2>/dev/null || find /staging/groups/bhaskar_group/ -maxdepth 2 -type d | head -50"
echo ""
echo "  # 查看 rho9 目录内容"
echo "  ls -lh /staging/groups/bhaskar_group/rho9/"
echo ""
echo "=========================================="
echo "💡 提示：你也可以直接运行以下命令："
echo "=========================================="
echo ""
echo "# 查看整个小组目录"
echo "ssh rho9@ap2001.chtc.wisc.edu 'ls -lh /staging/groups/bhaskar_group/'"
echo ""
echo "# 查看所有成员目录"
echo "ssh rho9@ap2001.chtc.wisc.edu 'ls -ld /staging/groups/bhaskar_group/*/'"
echo ""
echo "# 查看目录大小"
echo "ssh rho9@ap2001.chtc.wisc.edu 'du -sh /staging/groups/bhaskar_group/*/'"
echo ""

