#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   head -50 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   tail -100 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep -iE 'error|failed|exception|warning|invalid' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep -iE 'device|cuda|cpu|gpu' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep -E 'Starting Python|Running extraction|extract_all_latent_trajectories' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"
echo "  extract_all_latent_trajectories.py: error: argument --device: invalid choice: ''"
echo ""
echo "============================================================"

