#!/bin/bash
# 詳細檢查日誌，找出為什麼沒有成功提取

echo "============================================================"
echo "詳細日誌分析 - 找出失敗原因"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  查看日誌開始部分（看任務是否正常啟動）："
echo "   head -50 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "2️⃣  查看日誌結束部分（看錯誤信息）："
echo "   tail -100 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "3️⃣  查找所有錯誤和警告："
echo "   grep -iE 'error|failed|exception|warning|invalid' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "4️⃣  檢查DEVICE相關的信息："
echo "   grep -iE 'device|cuda|cpu|gpu' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "5️⃣  檢查是否有Python腳本啟動的記錄："
echo "   grep -E 'Starting Python|Running extraction|extract_all_latent_trajectories' /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "6️⃣  查看完整日誌（如果不太長的話）："
echo "   cat /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"
echo "從之前的錯誤日誌我們知道："
echo "  extract_all_latent_trajectories.py: error: argument --device: invalid choice: ''"
echo ""
echo "這表示 DEVICE 變量是空字串。"
echo "已修復的腳本應該能解決這個問題。"
echo "============================================================"

