#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   condor_q 2852953.0"
echo ""
echo "   condor_q -long 2852953.0 | grep -E 'JobCurrentStartDate|RemoteWallClockTime'"
echo ""
echo "   condor_tail 2852953.0 | tail -5"
echo ""
echo "   grep -i 'gpu\|cuda\|memory' ~/logs/extract_latents_v1_baseline.log | tail -10"
echo ""
echo "   condor_q -better-analyze 2852953.0 | grep -A 5 'Reason'"
echo ""
echo "============================================================"
echo ""
echo "============================================================"

