#!/bin/bash
# 診斷為什麼 sequence 2 處理很久

echo "============================================================"
echo "診斷 Sequence 2 處理緩慢問題"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  檢查任務是否還在運行（沒有卡死）："
echo "   condor_q 2852953.0"
echo ""
echo "2️⃣  查看任務運行了多久："
echo "   condor_q -long 2852953.0 | grep -E 'JobCurrentStartDate|RemoteWallClockTime'"
echo ""
echo "3️⃣  查看最新的輸出（看是否有任何進展）："
echo "   condor_tail 2852953.0 | tail -5"
echo ""
echo "4️⃣  檢查 GPU 使用情況（如果可能，通過 condor 日誌）："
echo "   grep -i 'gpu\|cuda\|memory' ~/logs/extract_latents_v1_baseline.log | tail -10"
echo ""
echo "5️⃣  檢查是否有錯誤（可能沒有輸出但任務失敗了）："
echo "   condor_q -better-analyze 2852953.0 | grep -A 5 'Reason'"
echo ""
echo "============================================================"
echo "可能的原因："
echo "  1. Sequence 2 真的需要很長時間（每個 sequence 需要 1-5 秒或更長）"
echo "  2. GPU 記憶體問題（可能卡在記憶體分配）"
echo "  3. 數據載入問題（I/O 瓶頸）"
echo "  4. 模型第一次運行需要更長時間"
echo ""
echo "建議："
echo "  - 如果任務狀態還是 'RUN'，通常表示還在運行"
echo "  - 可以再等幾分鐘看看是否有進展"
echo "  - 如果超過 10-15 分鐘沒有進展，可能需要檢查是否有問題"
echo "============================================================"

