#!/bin/bash
# 診斷當前任務狀態

echo "============================================================"
echo "診斷任務狀態"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  檢查任務是否還在運行："
echo "   condor_q -submitter rho9"
echo ""
echo "2️⃣  查看日誌最後部分（看是否有錯誤）："
echo "   tail -200 ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "3️⃣  檢查是否有 pandas 導入錯誤："
echo "   grep -i 'ImportError.*pandas\|ModuleNotFoundError.*pandas\|No module named.*pandas' ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "4️⃣  檢查是否有成功提取的記錄："
echo "   grep 'Saved:' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo "   grep 'Processing embryo' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo ""
echo "5️⃣  查看錯誤日誌："
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "6️⃣  檢查結果目錄是否存在（即使部分完成）："
echo "   ls -lh /staging/groups/bhaskar_group/rho9/model_latents/v1_baseline/ 2>/dev/null || echo '目錄不存在'"
echo ""
echo "============================================================"
echo "關於 pandas 問題的說明："
echo "  - pandas 安裝後仍顯示 MISSING 可能是檢測問題"
echo "  - 如果 Python 腳本能正常導入 pandas，就不會失敗"
echo "  - 需要查看完整日誌確認是否真的因為 pandas 失敗"
echo "============================================================"

