#!/bin/bash
# 诊断任务失败原因

echo "=== 诊断任务失败原因 ==="
echo ""
echo "在CHTC上运行以下命令："
echo ""
echo "# 1. 查看完整的condor日志（看任务执行过程）"
echo "cat ~/logs/extract_latents_v1_baseline.log | tail -200"
echo ""
echo "# 2. 查看输出日志（看处理到哪个embryo）"
echo "cat ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "# 3. 查看错误日志（看具体错误）"
echo "cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "# 4. 查看任务执行时间线（从日志中提取关键事件）"
echo "grep -E '(Job executing|Image size|MemoryUsage|Job terminated|ERROR|Error|Failed|failed)' ~/logs/extract_latents_v1_baseline.log | tail -50"
echo ""
echo "# 5. 查看内存使用变化（看是否内存溢出）"
echo "grep 'MemoryUsage\|Image size' ~/logs/extract_latents_v1_baseline.log | tail -30"
echo ""
echo "# 6. 查看最后处理的embryo（从输出日志中）"
echo "grep 'Processing embryo\|Found.*sequences\|Saved:' ~/logs/extract_latents_v1_baseline.out | tail -20"
echo ""
