#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   condor_q -submitter rho9"
echo ""
echo "   tail -200 ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep -i 'ImportError.*pandas\|ModuleNotFoundError.*pandas\|No module named.*pandas' ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep 'Saved:' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo "   grep 'Processing embryo' ~/logs/extract_latents_v1_baseline.out | tail -10"
echo ""
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo ""
echo "============================================================"
echo "============================================================"

