#!/bin/bash

echo ""
echo ""
echo "
echo "cat ~/logs/extract_latents_v1_baseline.log | tail -200"
echo ""
echo "
echo "cat ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "
echo "cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "
echo "grep -E '(Job executing|Image size|MemoryUsage|Job terminated|ERROR|Error|Failed|failed)' ~/logs/extract_latents_v1_baseline.log | tail -50"
echo ""
echo "
echo "grep 'MemoryUsage\|Image size' ~/logs/extract_latents_v1_baseline.log | tail -30"
echo ""
echo "
echo "grep 'Processing embryo\|Found.*sequences\|Saved:' ~/logs/extract_latents_v1_baseline.out | tail -20"
echo ""
