#!/bin/bash
# 最終修復和重新提交

echo "============================================================"
echo "最終修復和重新提交任務"
echo "============================================================"
echo ""
echo "已修復的問題："
echo "  1. ✅ GPUJobLength 從 'short' 改為 'long'（允許24+小時）"
echo "  2. ✅ MaxJobRuntime = 86400（24小時）"
echo ""
echo "待解決的問題："
echo "  - 任務卡在 sequence 2（需要進一步調查）"
echo ""
echo "============================================================"
echo "步驟 1: 上傳修復後的文件（在本地終端執行）"
echo "============================================================"
echo ""
echo "cd \"/Users/grnho/Desktop/Project IVF/Code/Autoencoder_Decoder_ver02\""
echo "scp extract_latents_from_home.sub rho9@ap2001.chtc.wisc.edu:~/"
echo ""
echo "============================================================"
echo "步驟 2: 在 CHTC 上重新提交（在 CHTC 上執行）"
echo "============================================================"
echo ""
echo "# 移除舊任務"
echo "condor_rm 2852953.0"
echo ""
echo "# 確認 submit 文件已更新"
echo "grep 'GPUJobLength' ~/extract_latents_from_home.sub"
echo ""
echo "# 重新提交"
echo "condor_submit ~/extract_latents_from_home.sub"
echo ""
echo "============================================================"
echo "關於 sequence 2 卡住的問題："
echo "  - 可能是數據載入問題"
echo "  - 可能是模型處理問題"
echo "  - 新任務會使用修復後的腳本，應該會更好"
echo "  - 如果還是卡住，可能需要進一步優化代碼"
echo "============================================================"

