#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo ""
echo "============================================================"
echo "============================================================"
echo ""
echo "cd \"/Users/grnho/Desktop/Project IVF/Code/Autoencoder_Decoder_ver02\""
echo "scp extract_latents_from_home.sub rho9@ap2001.chtc.wisc.edu:~/"
echo ""
echo "============================================================"
echo "============================================================"
echo ""
echo "
echo "condor_rm 2852953.0"
echo ""
echo "
echo "grep 'GPUJobLength' ~/extract_latents_from_home.sub"
echo ""
echo "
echo "condor_submit ~/extract_latents_from_home.sub"
echo ""
echo "============================================================"
echo "============================================================"

