#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   tail -200 ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "   grep -iE 'error|failed|exception|traceback|ImportError|ModuleNotFoundError' ~/logs/extract_latents_v1_baseline.out | tail -30"
echo ""
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "   condor_q -submitter rho9"
echo "   condor_history -limit 1 -submitter rho9 | grep extract"
echo ""
echo "   grep -E 'Processing|embryo|sequence' ~/logs/extract_latents_v1_baseline.out | tail -20"
echo ""
echo "   grep -E 'Starting Python|extract_all_latent_trajectories|usage:' ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"

