#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo "   ls -lht /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.* | head -5"
echo ""
echo "   tail -50 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "   condor_tail -f 2852953.0"
echo ""
echo "
echo ""
echo "   tail -100 ~/logs/extract_latents_v1_baseline.log"
echo ""
echo "============================================================"
echo "  - output = logs/extract_latents_v1_baseline.out"
echo "============================================================"

