#!/bin/bash
# 在整个 bhaskar_group staging 目录中搜索 latent vector 文件

echo "=========================================="
echo "🔍 搜索 Staging Group 中的 Latent Vector 文件"
echo "=========================================="
echo ""
echo "请先 SSH 连接到 CHTC 服务器："
echo ""
echo "  ssh rho9@ap2001.chtc.wisc.edu"
echo ""
echo "连接后，运行以下命令搜索 latent vector："
echo ""
echo "  # 搜索所有包含 'latent' 的文件和目录"
echo "  find /staging/groups/bhaskar_group/ -type f -iname '*latent*' 2>/dev/null"
echo "  find /staging/groups/bhaskar_group/ -type d -iname '*latent*' 2>/dev/null"
echo ""
echo "  # 搜索 .npy 文件（numpy 格式的 latent vector）"
echo "  find /staging/groups/bhaskar_group/ -type f -name '*.npy' 2>/dev/null | head -20"
echo ""
echo "  # 搜索 .pt 文件（PyTorch 格式）"
echo "  find /staging/groups/bhaskar_group/ -type f -name '*.pt' 2>/dev/null | head -20"
echo ""
echo "  # 搜索 model_latents 目录"
echo "  find /staging/groups/bhaskar_group/ -type d -name '*model_latents*' 2>/dev/null"
echo ""
echo "  # 查看 rho9 的 model_latents 目录内容"
echo "  ls -lhR /staging/groups/bhaskar_group/rho9/model_latents/ 2>/dev/null"
echo ""
echo "  # 搜索所有成员目录中的 latent 相关文件"
echo "  for dir in /staging/groups/bhaskar_group/*/; do"
echo "    echo \"=== \$(basename \$dir) ===\""
echo "    find \"\$dir\" -type f \\( -iname '*latent*' -o -name '*.npy' \\) 2>/dev/null | head -10"
echo "  done"
echo ""
echo "=========================================="
echo "💡 直接运行命令（推荐）："
echo "=========================================="
echo ""
echo "# 搜索所有 latent 相关文件"
echo "ssh rho9@ap2001.chtc.wisc.edu \"find /staging/groups/bhaskar_group/ -type f -iname '*latent*' 2>/dev/null\""
echo ""
echo "# 搜索所有 .npy 文件"
echo "ssh rho9@ap2001.chtc.wisc.edu \"find /staging/groups/bhaskar_group/ -type f -name '*.npy' 2>/dev/null | head -30\""
echo ""
echo "# 查看 rho9 的 model_latents 目录"
echo "ssh rho9@ap2001.chtc.wisc.edu \"ls -lh /staging/groups/bhaskar_group/rho9/model_latents/ 2>/dev/null || echo '目录不存在'\""
echo ""
echo "# 搜索所有 model_latents 目录"
echo "ssh rho9@ap2001.chtc.wisc.edu \"find /staging/groups/bhaskar_group/ -type d -name '*model_latents*' 2>/dev/null\""
echo ""




