#!/bin/bash
# 找出任務失敗的原因

echo "============================================================"
echo "查找任務失敗的原因"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  查看日誌最後部分（找出錯誤）："
echo "   tail -200 ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "2️⃣  搜索所有錯誤關鍵詞："
echo "   grep -iE 'error|failed|exception|traceback|ImportError|ModuleNotFoundError' ~/logs/extract_latents_v1_baseline.out | tail -30"
echo ""
echo "3️⃣  查看錯誤日誌："
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "4️⃣  檢查任務狀態："
echo "   condor_q -submitter rho9"
echo "   condor_history -limit 1 -submitter rho9 | grep extract"
echo ""
echo "5️⃣  查看是否有任何處理記錄（不同的格式）："
echo "   grep -E 'Processing|embryo|sequence' ~/logs/extract_latents_v1_baseline.out | tail -20"
echo ""
echo "6️⃣  查看 Python 腳本是否啟動："
echo "   grep -E 'Starting Python|extract_all_latent_trajectories|usage:' ~/logs/extract_latents_v1_baseline.out"
echo ""
echo "============================================================"

