#!/bin/bash

echo "=========================================="
echo "=========================================="
echo ""
echo ""
echo "  ssh rho9@ap2001.chtc.wisc.edu"
echo ""
echo ""
echo "
echo "  find /staging/groups/bhaskar_group/ -type f -iname '*latent*' 2>/dev/null"
echo "  find /staging/groups/bhaskar_group/ -type d -iname '*latent*' 2>/dev/null"
echo ""
echo "
echo "  find /staging/groups/bhaskar_group/ -type f -name '*.npy' 2>/dev/null | head -20"
echo ""
echo "
echo "  find /staging/groups/bhaskar_group/ -type f -name '*.pt' 2>/dev/null | head -20"
echo ""
echo "
echo "  find /staging/groups/bhaskar_group/ -type d -name '*model_latents*' 2>/dev/null"
echo ""
echo "
echo "  ls -lhR /staging/groups/bhaskar_group/rho9/model_latents/ 2>/dev/null"
echo ""
echo "
echo "  for dir in /staging/groups/bhaskar_group/*/; do"
echo "    echo \"=== \$(basename \$dir) ===\""
echo "    find \"\$dir\" -type f \\( -iname '*latent*' -o -name '*.npy' \\) 2>/dev/null | head -10"
echo "  done"
echo ""
echo "=========================================="
echo "=========================================="
echo ""
echo "
echo "ssh rho9@ap2001.chtc.wisc.edu \"find /staging/groups/bhaskar_group/ -type f -iname '*latent*' 2>/dev/null\""
echo ""
echo "
echo "ssh rho9@ap2001.chtc.wisc.edu \"find /staging/groups/bhaskar_group/ -type f -name '*.npy' 2>/dev/null | head -30\""
echo ""
echo "
echo ""
echo "
echo "ssh rho9@ap2001.chtc.wisc.edu \"find /staging/groups/bhaskar_group/ -type d -name '*model_latents*' 2>/dev/null\""
echo ""




