#!/bin/bash
# 找到正確的日誌位置

echo "============================================================"
echo "查找任務的實際日誌位置"
echo "============================================================"
echo ""
echo "請在 CHTC 上執行以下命令："
echo ""
echo "1️⃣  檢查 staging 目錄的日誌："
echo "   ls -lht /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.* | head -5"
echo ""
echo "2️⃣  查看 staging 日誌內容："
echo "   tail -50 /staging/groups/bhaskar_group/rho9/logs/extract_latents_v1_baseline.out 2>/dev/null"
echo ""
echo "3️⃣  使用 condor_tail 查看實時輸出（最可靠）："
echo "   condor_tail -f 2852953.0"
echo ""
echo "4️⃣  檢查任務的工作目錄日誌（如果可能）："
echo "   # 這需要在任務執行時才能訪問"
echo ""
echo "5️⃣  檢查 condor 日誌："
echo "   tail -100 ~/logs/extract_latents_v1_baseline.log"
echo ""
echo "============================================================"
echo "根據 submit 文件配置："
echo "  - output = logs/extract_latents_v1_baseline.out"
echo "  - transfer_output_remaps 將 logs 映射到 staging"
echo "  - 所以日誌可能在 staging 目錄"
echo "============================================================"

