#!/bin/bash
# 修復問題並重新提交任務

echo "============================================================"
echo "修復 Latent Extraction 任務問題"
echo "============================================================"
echo ""
echo "發現的問題："
echo "  1. 任務運行時間超過12小時被終止"
echo "  2. DEVICE 變量可能為空"
echo ""
echo "已修復："
echo "  ✓ 增加任務運行時間限制到24小時（+MaxJobRuntime = 86400）"
echo "  ✓ 修復 DEVICE 變量，確保有默認值"
echo ""
echo "============================================================"
echo "下一步："
echo ""
echo "1. 上傳修復後的文件到 CHTC："
echo "   scp extract_latents.sh extract_latents_from_home.sub \\"
echo "       rho9@ap2001.chtc.wisc.edu:~/"
echo ""
echo "2. 或者直接上傳到 staging："
echo "   scp extract_latents.sh \\"
echo "       rho9@ap2001.chtc.wisc.edu:/staging/groups/bhaskar_group/rho9/"
echo ""
echo "3. 在 CHTC 上釋放當前任務（如果需要重新提交）："
echo "   condor_release 2851275.0"
echo ""
echo "4. 或者移除舊任務並重新提交："
echo "   condor_rm 2851275.0"
echo "   condor_submit extract_latents_from_home.sub"
echo ""
echo "============================================================"

