#!/bin/bash
# 修復 CHTC 上損壞的腳本

echo "============================================================"
echo "修復 CHTC 上損壞的腳本"
echo "============================================================"
echo ""
echo "問題：腳本第一行包含錯誤的文本 '[需要我提供完整的更新后的脚本内容]'"
echo ""
echo "請在 CHTC 上執行以下步驟："
echo ""
echo "1. 檢查當前腳本的第一行："
echo "   head -1 /staging/groups/bhaskar_group/rho9/extract_latents.sh"
echo ""
echo "2. 如果第一行不是 '#!/bin/bash'，需要修復："
echo "   # 備份原文件"
echo "   cp /staging/groups/bhaskar_group/rho9/extract_latents.sh /staging/groups/bhaskar_group/rho9/extract_latents.sh.backup"
echo ""
echo "3. 重新上傳正確的腳本（在本地終端執行）："
echo "   cd \"/Users/grnho/Desktop/Project IVF/Code/Autoencoder_Decoder_ver02\""
echo "   scp extract_latents.sh rho9@ap2001.chtc.wisc.edu:/staging/groups/bhaskar_group/rho9/"
echo ""
echo "4. 或者在 CHTC 上直接修復第一行："
echo "   sed -i '1s/.*/#!/bin/bash/' /staging/groups/bhaskar_group/rho9/extract_latents.sh"
echo ""
echo "5. 驗證修復："
echo "   head -5 /staging/groups/bhaskar_group/rho9/extract_latents.sh"
echo ""
echo "6. 重新提交任務（如果需要）："
echo "   condor_rm 2852953.0  # 移除當前任務"
echo "   condor_submit ~/extract_latents_from_home.sub"
echo ""
echo "============================================================"

