#!/bin/bash

echo "============================================================"
echo "============================================================"
echo ""
echo ""
echo ""
echo "============================================================"
echo ""
echo "   scp extract_latents.sh extract_latents_from_home.sub \\"
echo "       rho9@ap2001.chtc.wisc.edu:~/"
echo ""
echo "   scp extract_latents.sh \\"
echo "       rho9@ap2001.chtc.wisc.edu:/staging/groups/bhaskar_group/rho9/"
echo ""
echo "   condor_release 2851275.0"
echo ""
echo "   condor_rm 2851275.0"
echo "   condor_submit extract_latents_from_home.sub"
echo ""
echo "============================================================"

