#!/bin/bash
# 調查任務為什麼卡住

echo "============================================================"
echo "任務已經運行 62 分鐘仍卡在 sequence 2，這不正常"
echo "============================================================"
echo ""
echo "請執行以下診斷命令："
echo ""
echo "1️⃣  檢查任務狀態（確認是否真的卡住）："
echo "   condor_q 2852953.0"
echo ""
echo "2️⃣  查看任務詳細狀態（看是否有錯誤信息）："
echo "   condor_q -better-analyze 2852953.0"
echo ""
echo "3️⃣  檢查 condor 日誌中是否有錯誤："
echo "   grep -iE 'error|failed|evicted|held|memory|gpu' ~/logs/extract_latents_v1_baseline.log | tail -20"
echo ""
echo "4️⃣  查看錯誤日誌："
echo "   cat ~/logs/extract_latents_v1_baseline.err"
echo ""
echo "============================================================"
echo "可能的問題："
echo "  1. GPU 記憶體不足（可能卡在記憶體分配）"
echo "  2. 數據載入問題（I/O 瓶頸或文件損壞）"
echo "  3. 模型前向傳播卡住"
echo "  4. 任務被資源限制（但狀態還顯示 RUN）"
echo ""
echo "建議："
echo "  如果確認任務卡住且沒有任何進展，可能需要："
echo "  1. 終止任務: condor_rm 2852953.0"
echo "  2. 檢查錯誤日誌找出問題"
echo "  3. 可能需要調整批次大小或檢查數據"
echo "============================================================"

